name: flutter_oorbswallpaper_app
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  # 通用
  hzy_common_module:
    path: ../../thirdlib/hzy_common_module/
    flutter_localizations:
    sdk: flutter
  # # Flutter 小部件可自动调整文本大小以完美适合其边界。
  # auto_size_text: 3.0.0
  # # 用于加载和缓存网络图像的 Flutter 库。  还可以与占位符和错误小部件一起使用。
  # cached_network_image: 3.2.3
  # # 用于将国家/地区代码转换为表情符号标志的 dart 库。
  # emoji_flag_converter: 1.1.0
  # # 一个 Dart 包，有助于实现基于值的相等，而无需显式覆盖 == 和 hashCode。
  # equatable: 2.0.5
  # # 一个简单但完全可定制的 flutter 评级栏，其中还包括一个评级栏指示器，支持任何评级部分。
  # flutter_rating_bar: 4.0.1
  # # 带有颤动动画的加载指示器的集合。  深受 @tobiasahlin 的 SpinKit 启发。
  # flutter_spinkit: 5.2.0
  # # Font Awesome 图标包可作为 Flutter 图标使用。  提供 1600 个附加图标以在您的应用程序中使用。
  # font_awesome_flutter: 10.5.0
  # # 使用 fonts.google.com 字体的 Flutter 包。  支持 HTTP 获取、缓存和资源捆绑。
  # google_fonts: 5.1.0
  # # 将网络或临时文件中的图像和视频保存到外部存储。  图像和视频都将在 Android 图库和 iOS 照片中可见。
  # gallery_saver: 2.3.2
  # google_mobile_ads:
  #   git:
  #     url: https://github.com/asmengistu/googleads-mobile-flutter
  #     ref: b943dffb925bf7a527a981d12d34a5797c34a37d
  #     path: packages/google_mobile_ads/
  # intl: 0.17.0
  # json_path: 0.3.1
  # lottie: 1.2.1
  # page_transition: 2.0.4
  # photo_view: ^0.13.0
  # smooth_page_indicator: 1.0.0+2
  # timeago: 3.1.0
  # url_launcher: 6.0.15
  # webviewx: 0.2.1

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/
