export 'jingdong_home_v.dart';
// 京东demo
export 'account/views/login_view.dart';
export 'account/views/pwdlogin_view.dart';
export 'account/views/register_view.dart';
export 'account/views/smslogin_view.dart';
export 'news/views/news_view.dart';
export './browse_history/browse_history_view.dart';
export './account_set/account_set_view.dart';
export './order/order_view.dart';
