name: flutter_mitchkoko
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "https://github.com/mitchkoko"
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  # 可滑动列表项的 Flutter 实现，具有可关闭的定向滑动操作。
  flutter_slidable: ^3.0.0
  # 用纯 Dart 编写的轻量级且速度极快的键值数据库。  使用 AES-256 进行严格加密。
  hive: ^2.2.3
  # Hive 的扩展。  使在 Flutter 应用程序中使用 Hive 变得更加容易。
  hive_flutter: ^1.1.0
  # Flutter 热图日历的灵感来自 github 贡献图，包括传统模式/日历模式。
  flutter_heatmap_calendar: ^1.0.5

  # 颤振指南针。  航向范围为 0-360，0 为北。
  flutter_compass: ^0.8.0
  # Firebase Core 的 Flutter 插件，可连接到多个 Firebase 应用程序。
  firebase_core: ^2.15.1
  # 适用于 Firebase Auth 的 Flutter 插件，支持使用密码、电话号码和 Google、Facebook 和 Twitter 等身份提供商进行 Android 和 iOS 身份验证。
  firebase_auth: ^4.9.0
  # 使用 fonts.google.com 字体的 Flutter 包。
  # 支持 HTTP 获取、缓存和资源捆绑。
  google_fonts: ^5.1.0
  # 通用
  hzy_common_module:
    path: ../../thirdlib/hzy_common_module/

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/ModernSmartHomeUI/images/
    - assets/EmailLoginLogoutUI/images/
    - assets/DonutAppUI/images/
    - assets/CompassUI/images/
    - assets/HabitTrackerUI/images/
    - assets/screenshots/
