name: flutter_mitchkoko
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "https://github.com/mitchkoko"
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  # 使用 fonts.google.com 字体的 Flutter 包。
  # 支持 HTTP 获取、缓存和资源捆绑。
  google_fonts: ^5.1.0
  # 通用
  hzy_common_module:
    path: ../../thirdlib/hzy_common_module/

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/ModernSmartHomeUI/images/
    - assets/screenshots/
