name: flutter_mitchkoko
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "https://github.com/mitchkoko"
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  # 通用
  hzy_common_module:
    path: ../../thirdlib/hzy_common_module/

  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/
