name: demo_jingdong
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  # 瀑布流
  waterfall_flow: ^3.0.2
  # 扩展NestedScrollView
  extended_nested_scroll_view: ^6.1.2
  # 加载更多列表支持ListView,GridView以及瀑布流。
  loading_more_list: ^6.0.0

  hzy_common_module:
    path: ../../thirdlib/hzy_common_module/
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/jingdong_demos/
    - assets/images/jingdong_demos/home/
    - assets/images/jingdong_demos/login/
    - assets/images/jingdong_demos/news/
    - assets/images/jingdong_demos/product/
    - assets/images/jingdong_demos/store/
    - assets/images/scroll_demos/
