name: demo_jingdong
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: "http"
environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter_animated_dialog: ^2.0.1
  easy_refresh: ^3.3.2+1
  # 瀑布流
  waterfall_flow: ^3.0.2
  # 强大的Sliver扩展库, 包括 SliverToNestedScrollBoxAdapter, SliverPinnedPersistentHeader,
  # SliverPinnedToBoxAdapter 和 ExtendedSliverAppbar.
  extended_sliver: ^2.1.3
  # 扩展NestedScrollView
  extended_nested_scroll_view: ^6.1.2
  # 加载更多列表支持ListView,GridView以及瀑布流。
  loading_more_list: ^6.0.0

  hzy_common_module:
    path: ../../thirdlib/hzy_common_module/
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/home/
    - assets/images/login/
    - assets/images/news/
    - assets/images/product/
    - assets/images/store/
    - assets/images/discover/
    - assets/images/loading/
    - assets/json/mock-data/functionId/@new/tab/xinpin/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getNewsTrendsTabDetails/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getRecommendNewFeedsList/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/1/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/7/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/9/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/19/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/20/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/22/
    - assets/json/mock-data/functionId/@new/tab/xinpin/getTabProductsList/95/
    - assets/json/mock-data/functionId/@new/tab/person/
    - assets/json/mock-data/functionId/@new/tab/person/address/
    - assets/json/mock-data/functionId/@new/tab/person/browseHistory/
    - assets/json/mock-data/functionId/@new/tab/person/favorite/
    - assets/json/mock-data/functionId/@new/tab/person/recommend/
    - assets/json/mock-data/functionId/@new/tab/person/order/
    - assets/json/mock-data/functionId/@new/tab/person/order/allOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/cancleOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/completedOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/wait4DeliveryOrder/
    - assets/json/mock-data/functionId/@new/tab/person/order/wait4PaymentOrder/
    - assets/json/mock-data/functionId/@new/tab/discFollow/
    - assets/json/mock-data/functionId/@new/tab/discFollow/discFollowNextContent/
    - assets/json/mock-data/functionId/@new/tab/discovery/
    - assets/json/mock-data/functionId/@new/tab/discovery/follow/
    - assets/json/mock-data/functionId/@new/tab/discovery/feedStream/
    - assets/json/mock-data/functionId/@new/tab/category/
    - assets/json/mock-data/functionId/@new/tab/category/cid/
    - assets/json/mock-data/functionId/@new/tab/category/cid/0/
    - assets/json/mock-data/functionId/@new/tab/category/cid/300014703/
    - assets/json/mock-data/functionId/@new/tab/category/cid/300015294/
    - assets/json/mock-data/functionId/@new/tab/category/cid/300015359/
    - assets/json/mock-data/functionId/@new/tab/cart/
    - assets/json/mock-data/functionId/@new/tab/cart/confirmOrder/
    - assets/json/mock-data/functionId/@new/tab/cart/uniformRecommend/
    - assets/json/mock-data/functionId/@new/tab/home/
    - assets/json/mock-data/functionId/@new/tab/home/hours/
    - assets/json/mock-data/functionId/@new/tab/home/category/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/234/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/237/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/246/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/248/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/700/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/1761/
    - assets/json/mock-data/functionId/@new/tab/home/category/pcid/2230/
    - assets/json/mock-data/functionId/@new/tab/home/category/pmid/
    - assets/json/mock-data/functionId/@new/tab/home/category/pmid/142/
