name: hzy_normal_network
description: 火之夜网络请求封装库
version: 0.0.1
homepage: https://gitee.com/tengteng_fan/hzy_normal_network.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 一个强大的 HTTP 网络包，支持拦截器、中止和取消请求、自定义适配器、转换器等。
  dio: ^5.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
